### ISSUE TITLE
500 Error when adding new comic

### ISSUE THREAD

**Issue by quark5980** [ferretcomp/mylar#10]
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "c:\Mylar\lib\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "c:\Mylar\lib\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "c:\Mylar\lib\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\Mylar\mylar\webserve.py", line 76, in home
    comics = helpers.havetotals()
  File "c:\Mylar\mylar\helpers.py", line 1369, in havetotals
    "ComicPublished":  re.sub('(N)', '', comic['ComicPublished']).strip(),
  File "c:\Python27\lib\re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by quark5980** [comment]
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "c:\Mylar\lib\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "c:\Mylar\lib\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "c:\Mylar\lib\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\Mylar\mylar\webserve.py", line 76, in home
    comics = helpers.havetotals()
  File "c:\Mylar\mylar\helpers.py", line 1369, in havetotals
    "ComicPublished":  re.sub('(N)', '', comic['ComicPublished']).strip(),
  File "c:\Python27\lib\re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
