### ISSUE TITLE
Manual Post Process Error

### ISSUE THREAD

**Issue by quark5980** [ferretcomp/mylar#7]
When trying to run a manual post process

2017-06-16 19:47:12	ERROR	Uncaught exception: Traceback (most recent call last):
File "c:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "c:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "c:\Mylar\mylar\PostProcessor.py", line 910, in Process
if (mylar.NOMATCHSORT == 1):
AttributeError: 'module' object has no attribute 'NOMATCHSORT'

**Comment by ferretcomp** [comment]
Yup, I broke it. Latest release will fix.;
